apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "buildmaster.fullname" . }}
  labels:
    {{- include "buildmaster.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "buildmaster.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "buildmaster.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
          - name: BUILDMASTER_SQL_CONNECTION_STRING
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-configmap
                key: BUILDMASTER_SQL_CONNECTION_STRING

          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
                
          volumeMounts:
          - name:  {{ include "buildmaster.fullname" . }} 
            mountPath: /var/buildmaster/artifacts
          
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
      - name: {{ include "buildmaster.fullname" . }} 
        persistentVolumeClaim:
          claimName:  {{ include "buildmaster.fullname" . }} 