trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: aws

steps:
  # Step 1: Install AWS CLI
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      sudo apt-get update
      sudo apt-get install -y awscli
      aws --help
    displayName: 'Install AWS CLI'

  # Step 2: Configure AWS Credentials
  - script: |
      aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
      aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
      aws configure set region $(region)
    displayName: 'Configure AWS Credentials'
