trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: aws  # AWS credential variables stored in a variable group

stages:
  - stage: CI
    jobs:
      - job: Build
        steps:
          # Step 1: Install AWS CLI
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true

          - script: |
              sudo apt-get update
              sudo apt-get install -y awscli
              #sudo apt-get install -y unzip
            displayName: 'Install AWS CLI'

          # Step 2: Configure AWS Credentials using variables from the group
          - script: |
              aws configure set aws_access_key_id $(accesskey)
              aws configure set aws_secret_access_key $(secretkey)
              aws configure set region $(region)
            displayName: 'Configure AWS Credentials'

          # Step 3: Install Helm
          - script: |
              curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
            displayName: 'Install Helm'

          - script: |
              helm version --short
            displayName: 'Check Helm Version'

          # Step 4: Install Helm S3 Plugin
          - script: |
              helm plugin install https://github.com/hypnoglow/helm-s3.git
            displayName: 'Install Helm S3 Plugin'

          # Step 5: Increment Chart Version Based on Commit
          - script: |
              # Extract current chart version from Chart.yaml
              current_version=$(grep '^version:' buildmaster/Chart.yaml | awk '{print $2}')
              echo "Current version: $current_version"
              
              # Increment the patch version (you can modify to increment minor or major)
              IFS='.' read -r major minor patch <<< "$current_version"
              new_patch=$((patch+1))
              new_version="$major.$minor.$new_patch"
              echo "New version: $new_version"
              
              # Update Chart.yaml with new version
              sed -i "s/^version:.*/version: $new_version/" buildmaster/Chart.yaml
              
              # Commit the version change (this step assumes git is configured in the pipeline)
              git branch -a 
              git config --global user.email "julestl@yahoo.fr"
              git config --global user.name "chejuro1"
              git add buildmaster/Chart.yaml
              git commit -m "Increment chart version to $new_version"
              git push origin HEAD
            displayName: 'Increment Chart Version'

          # Step 6: Initialize and Add S3 Repo
          - script: |
              helm s3 init s3://chejurhelmchart/Buildmaster
              helm repo add Buildmaster s3://chejurhelmchart/Buildmaster
            displayName: 'Initialize and Add Helm Repo'
          
          # Step 7: Create Helm Chart and Push to S3
          - script: |
              printenv
              helm package buildmaster  # Package the Helm chart with updated version
              echo "Packaging Helm chart with version: $new_version"
              newchart=$(echo buildmaster-$new_version.tgz)
              echo $newchart
              helm s3 push $newchart Buildmaster  # Push the chart to the S3 Helm repo
            displayName: 'Package and Push Helm Chart'

  # - stage: CI
  #   jobs:
  #     - job: Build
  #       steps:
  #       # Step 5: Initialize and Add S3 Repo
  #         - script: |
  #             helm s3 init s3://chejurhelmchart/Buildmaster
  #             helm repo add Buildmaster s3://chejurhelmchart/Buildmaster
  #           displayName: 'Initialize and Add Helm Repo'


