# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
 - task: AWSCLI@1
   inputs:
     awsCredentials: 'aws_ecr'
     regionName: 'us-east-1'
     awsCommand: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
             

   displayName: 'helm charts in S3 '

 
 

  
