apiVersion: v1
kind: Service
metadata:
  name: {{ include "buildmaster.fullname" . }}
  labels:
    {{- include "buildmaster.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "buildmaster.selectorLabels" . | nindent 4 }}
