apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "proget.fullname" . }}
spec:
  storageClassName: {{ .Values.StorageClass.name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi